### PR TITLE
chore: test PHP 7.1

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks for you pull request. 

But Laravel 5.6 only supports php >= 7.1.3. Sorry.

**Comment by DanielRuf** [comment]
> But Laravel 5.6 only supports php >= 7.1.3. Sorry.

This uses the latest release of 7.1, so it will be 7.1.3+ or you need another string, "7.1.3" only checks "7.1.3" and not a newer release.

**Comment by DanielRuf** [comment]
See https://travis-ci.org/nunomaduro/laravel-code-analyse/jobs/398931408#L486 which is 7.1.11.

**Comment by nunomaduro** [comment]
You are right! Thank you so much.

**Pull request merged**
